#Requires -Modules Pester
<#
.SYNOPSIS
    XAML integrity tests for GA-AppLocker Dashboard.
.DESCRIPTION
    Verifies that:
    - All x:Name attributes referenced in code-behind exist in MainWindow.xaml
    - All button Tags map to valid Invoke-ButtonAction switch cases
    - All panels referenced in Set-ActivePanel exist
    - Navigation buttons map to correct panels
    Runs headless - no WPF runtime required.
#>

BeforeAll {
    $script:ProjectRoot = Join-Path $PSScriptRoot '..\..'
    $script:XamlPath = Join-Path $script:ProjectRoot 'GA-AppLocker\GUI\MainWindow.xaml'
    $script:GuiPath = Join-Path $script:ProjectRoot 'GA-AppLocker\GUI'

    # Parse XAML as XML and extract all x:Name values
    $rawXaml = Get-Content $script:XamlPath -Raw
    # Remove the xmlns default namespace to simplify XPath queries
    $cleanXaml = $rawXaml -replace 'xmlns="[^"]*"', ''
    [xml]$script:Xaml = $cleanXaml

    # Extract all x:Name values from XAML using regex (more reliable than XPath with namespaces)
    $script:AllXamlNames = [System.Collections.Generic.HashSet[string]]::new()
    $nameMatches = [regex]::Matches($rawXaml, 'x:Name="(\w+)"')
    foreach ($m in $nameMatches) {
        $script:AllXamlNames.Add($m.Groups[1].Value) | Out-Null
    }

    # Extract all FindName references from all GUI .ps1 files
    function Get-FindNameReferences {
        param(
            [string]$FilePath,
            [string[]]$ExcludeNames = @()
        )
        $content = Get-Content $FilePath -Raw
        $matches = [regex]::Matches($content, "FindName\(['""](\w+)['""]\)")
        $names = @()
        foreach ($m in $matches) {
            $val = $m.Groups[1].Value
            if ($val -notin $ExcludeNames) {
                $names += $val
            }
        }
        return $names | Sort-Object -Unique
    }

    # Elements referenced via FindName but NOT in MainWindow.xaml because they are:
    # - In dialog/wizard XAML (dynamically loaded at runtime)
    # - Dynamically created in code (chart bars, etc.)
    # - Intentionally removed from XAML (dead code cleanup)
    # These are ALL null-guarded in code, so missing FindName returns $null safely.
    # Complete list of elements referenced via FindName that are NOT in MainWindow.xaml.
    # They live in: dialog XAML (built at runtime), wizard XAML, dynamic code, or removed elements.
    # All are null-guarded — missing FindName returns $null safely.
    # Generated by scanning ALL GUI/*.ps1 FindName calls vs MainWindow.xaml x:Name attributes.
    $script:DialogOnlyElements = @(
        # Rule Generation Wizard (RuleGenerationWizard.ps1 builds its own XAML)
        'WizardBtnBack', 'WizardBtnCancel', 'WizardBtnClose', 'WizardBtnGenerate',
        'WizardBtnMinimize', 'WizardBtnNext',
        'WizardCboAction', 'WizardCboDedupeMode', 'WizardCboMode', 'WizardCboPubLevel',
        'WizardCboStatus', 'WizardChkSkipDlls', 'WizardChkSkipShellScripts',
        'WizardChkSkipUnsigned', 'WizardChkSkipWshScripts',
        'WizardDgSampleRules', 'WizardIndicator1', 'WizardIndicator2', 'WizardIndicator3',
        'WizardPanelComplete', 'WizardPanelProgress', 'WizardPreviewContent',
        'WizardPreviewLoading', 'WizardProgress', 'WizardProgressBar',
        'WizardStep1', 'WizardStep2', 'WizardStep3',
        'WizardTxtDeduped', 'WizardTxtDllCount', 'WizardTxtDuration',
        'WizardTxtExeCount', 'WizardTxtExistingRules', 'WizardTxtHashRules',
        'WizardTxtNewRules', 'WizardTxtProgress', 'WizardTxtPublisherRules',
        'WizardTxtResult', 'WizardTxtScriptCount', 'WizardTxtSignedArtifacts',
        'WizardTxtSkipped', 'WizardTxtStatus', 'WizardTxtToProcess',
        'WizardTxtTotalArtifacts', 'WizardTxtUnsignedArtifacts',
        'RuleWizardOverlay',
        # Setup Wizard (SetupWizard.ps1 builds its own XAML)
        'AutoDetectDomainBtn', 'BackBtn', 'CheckPrereqsBtn', 'ConfigureWinRMBtn',
        'CreateADStructure', 'CreateAuditGPO', 'CreateEnforceGPO', 'CreateGPOsBtn',
        'CredentialFields', 'CredentialUsername', 'DomainController', 'DomainName',
        'NextBtn', 'OUList', 'PrereqAdmin', 'PrereqADModule', 'PrereqGPModule',
        'PrereqPowerShell', 'RefreshOUsBtn', 'SearchBase', 'SelectedOUCount',
        'SkipBtn', 'SkipGPOBtn', 'SkipWinRMBtn', 'StepIndicator',
        'SummaryCredentials', 'SummaryDomain', 'SummaryGPOs', 'SummaryTargets',
        'SummaryWinRM', 'TestCredentialsBtn', 'UseCurrentCreds', 'UseSpecificCreds',
        'WinRMStatus',
        # Dialog elements (ScannerDialogs, RulesDialogs — built dynamically)
        'BtnCancel', 'BtnClose', 'BtnMinimize', 'BtnOK',
        'BtnSelectAll', 'BtnSelectNone',
        'MachineStack', 'TxtFilter', 'TxtSelectionCount',
        'BtnCompareVersions', 'BtnRestoreVersion', 'TxtVersionDetails', 'VersionsList',
        # Rules panel dialogs (Change Action/Group/AddToPolicy)
        'CboGroup', 'CboStatus', 'CboTargetGroup', 'RbAllow', 'RbDeny', 'RbRuleAllow',
        'PolicyRulesDataGrid', 'SelectedRulesCount',
        # Policy Compare tab elements (dynamically populated)
        'BtnExportDiffReport', 'CboCompareSource', 'CboCompareTarget',
        'CboComparePolicy1', 'CboComparePolicy2',
        'DiffDataGrid', 'TxtDiffSummary',
        # GlobalSearch (Helpers/GlobalSearch.ps1 — popup elements)
        'BtnClearGlobalSearch', 'GlobalSearchBox', 'GlobalSearchPlaceholder',
        'GlobalSearchPopup', 'GlobalSearchResults',
        # ThemeManager (Helpers/ThemeManager.ps1 — toggle elements)
        'ThemeLabelDark', 'ThemeLabelLight', 'ThemeToggleBorder', 'ThemeToggleKnob',
        # Scanner elements removed/in dynamic tabs (null-guarded)
        'ArtifactsDropZone', 'BtnBrowsePath', 'BtnResetPaths',
        'BtnCreateSchedule', 'BtnDeleteSchedule', 'BtnRunScheduleNow',
        'BtnDeselectAllArtifacts', 'BtnSelectAllArtifacts',
        'BtnGenerate', 'BtnGenerateFromArtifacts',
        'CboPublisherLevel', 'CboRuleTargetGroup', 'CboScheduleType', 'CboUnsignedMode',
        'ChkExcludeDll', 'ChkExcludeJs', 'ChkExcludeScripts', 'ChkExcludeUnsigned',
        'ChkSaveResults', 'ChkScheduleEnabled',
        'ChkSkipDlls', 'ChkSkipShellScripts', 'ChkSkipUnsigned', 'ChkSkipWshScripts',
        'ScheduledScansList', 'TxtScheduleName', 'TxtScheduleTime',
        'TxtScanName', 'TxtScanPaths',
        'TxtArtifactFilteredCount', 'TxtArtifactTotalCount', 'TxtSelectedArtifactCount',
        'ArtifactDataGrid', 'ScanSignedCount', 'ScanUnsignedCount',
        # Rules panel elements in dynamic contexts
        'RbManualRuleAllow', 'RbManualRuleDeny', 'RulesDataGrid',
        'TxtRuleFilteredCount', 'TxtRuleTotalDisplayCount',
        'TxtSelectedPolicyName', 'TxtPolicyRuleCount',
        # Dashboard chart elements (referenced but not in XAML — null-guarded)
        'ChartBarApproved', 'ChartBarPending', 'ChartBarRejected', 'ChartBarReview',
        'ChartLabelApproved', 'ChartLabelPending', 'ChartLabelRejected', 'ChartLabelReview',
        'ChartTotalRules',
        'ChartBarPublisher', 'ChartBarHash', 'ChartBarPath',
        'ChartLabelPublisher', 'ChartLabelHash', 'ChartLabelPath',
        # Misc
        'CboAction'
    )

    # Extract Invoke-ButtonAction switch cases from MainWindow.xaml.ps1
    $script:MainWindowCode = Get-Content (Join-Path $script:GuiPath 'MainWindow.xaml.ps1') -Raw
    $script:ActionCases = [System.Collections.Generic.HashSet[string]]::new()
    $caseMatches = [regex]::Matches($script:MainWindowCode, "'(\w+)'\s*\{")
    foreach ($m in $caseMatches) {
        $script:ActionCases.Add($m.Groups[1].Value) | Out-Null
    }

    # Extract all button Tag values from XAML
    $script:ButtonTags = [System.Collections.Generic.HashSet[string]]::new()
    $tagMatches = [regex]::Matches($rawXaml, '<Button[^>]*\bTag="(\w+)"')
    foreach ($m in $tagMatches) {
        $script:ButtonTags.Add($m.Groups[1].Value) | Out-Null
    }
}

Describe 'XAML Integrity - Panel Definitions' {
    Context 'All panels referenced in Set-ActivePanel exist in XAML' {
        $panels = @(
            'PanelDashboard', 'PanelDiscovery', 'PanelScanner',
            'PanelRules', 'PanelPolicy', 'PanelDeploy',
            'PanelSoftware', 'PanelSettings', 'PanelSetup', 'PanelAbout'
        )

        It 'Panel "<_>" exists in XAML' -ForEach $panels {
            $script:AllXamlNames | Should -Contain $_
        }
    }

    Context 'All navigation buttons exist in XAML' {
        $navButtons = @(
            'NavDashboard', 'NavDiscovery', 'NavScanner', 'NavRules',
            'NavPolicy', 'NavDeploy', 'NavSoftware',
            'NavSettings', 'NavSetup', 'NavAbout'
        )

        It 'Nav button "<_>" exists in XAML' -ForEach $navButtons {
            $script:AllXamlNames | Should -Contain $_
        }
    }

    Context 'Nav button text labels exist' {
        $navTextLabels = @(
            'NavDashboardText', 'NavDiscoveryText', 'NavScannerText', 'NavRulesText',
            'NavPolicyText', 'NavDeployText', 'NavSoftwareText',
            'NavSettingsText', 'NavSetupText', 'NavAboutText'
        )

        It 'Text label "<_>" exists in XAML' -ForEach $navTextLabels {
            $script:AllXamlNames | Should -Contain $_
        }
    }
}

Describe 'XAML Integrity - Button Action Dispatcher' {
    Context 'Button Tags map to valid action cases' {
        # Tags that are used as filters (FilterRulesAll, etc.) not as button actions
        $filterTags = @('Active', 'NavDiscovery', 'NavScanner', 'NavRules', 'NavPolicy', 'NavDeploy')

        It 'Action tag "<_>" has a case in Invoke-ButtonAction' -ForEach ($script:ButtonTags | Where-Object {
            $_ -notmatch '^FilterRules' -and $_ -notmatch '^FilterPolicies' -and
            $_ -notmatch '^FilterJobs' -and $_ -notin $filterTags
        }) {
            $script:ActionCases | Should -Contain $_
        }
    }

    Context 'Navigation actions are all handled' {
        $navActions = @(
            'NavDashboard', 'NavDiscovery', 'NavScanner', 'NavRules',
            'NavPolicy', 'NavDeploy', 'NavSoftware',
            'NavSettings', 'NavSetup', 'NavAbout'
        )

        It 'Action "<_>" is handled in dispatcher' -ForEach $navActions {
            $script:ActionCases | Should -Contain $_
        }
    }
}

Describe 'XAML Integrity - Dashboard Panel Elements' {
    Context 'Dashboard stats elements' {
        $dashElements = @(
            'StatMachines', 'StatArtifacts', 'StatRules',
            'StatPending', 'StatApproved', 'StatRejected', 'StatPolicies',
            'DashRecentScans', 'DashPendingRules'
        )

        It 'Element "<_>" exists in XAML' -ForEach $dashElements {
            $script:AllXamlNames | Should -Contain $_
        }
    }

    Context 'Getting Started buttons' {
        $gsButtons = @(
            'BtnGettingStarted1', 'BtnGettingStarted2', 'BtnGettingStarted3',
            'BtnGettingStarted4', 'BtnGettingStarted5'
        )

        It 'Button "<_>" exists in XAML' -ForEach $gsButtons {
            $script:AllXamlNames | Should -Contain $_
        }
    }
}

Describe 'XAML Integrity - Discovery Panel Elements' {
    $discoveryElements = @(
        'BtnRefreshDomain', 'BtnTestConnectivity',
        'DiscoveryDomainLabel', 'DiscoveryMachineCount',
        'MachineDataGrid', 'OUTreeView', 'MachineFilterBox',
        'BtnFilterAll', 'BtnFilterWorkstations', 'BtnFilterServers',
        'BtnFilterDCs', 'BtnFilterOnline',
        'BtnSelectAllOUs', 'BtnClearOUs'
    )

    It 'Element "<_>" exists in XAML' -ForEach $discoveryElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - Scanner Panel Elements' {
    $scannerElements = @(
        'BtnStartScan', 'BtnStopScan', 'BtnImportArtifacts', 'BtnExportArtifacts',
        'ScanStatusLabel', 'ScanArtifactCount',
        'ChkScanLocal', 'ChkScanRemote',
        'ChkIncludeAppx', 'ChkIncludeEventLogs', 'ChkIncludeHighRisk',
        'ChkSkipDllScanning', 'ChkSkipWshScanning', 'ChkSkipShellScanning',
        'BtnSelectMachines', 'BtnRefreshScans', 'BtnLoadScan', 'BtnDeleteScan'
    )

    It 'Element "<_>" exists in XAML' -ForEach $scannerElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - Rules Panel Elements' {
    $rulesElements = @(
        'BtnLaunchRuleWizard', 'BtnCreateManualRule',
        'BtnExportRulesXml', 'BtnExportRulesCsv', 'BtnImportRulesXml',
        'BtnRefreshRules', 'BtnApproveRule', 'BtnRejectRule', 'BtnReviewRule',
        'BtnDeleteRule', 'BtnViewRuleDetails',
        'BtnChangeAction', 'BtnChangeGroup',
        'BtnAddCommonDenyRules', 'BtnAddDenyBrowserRules',
        'BtnAddAdminAllowRules', 'BtnRemoveDuplicateRules',
        'TxtRuleFilter', 'ChkSelectAllRules', 'TxtSelectedRuleCount',
        'BtnFilterAllRules', 'BtnFilterPublisher', 'BtnFilterHash', 'BtnFilterPath',
        'BtnFilterPending', 'BtnFilterApproved', 'BtnFilterRejected',
        'TxtRuleTotalCount', 'TxtRulePendingCount', 'TxtRuleApprovedCount', 'TxtRuleRejectedCount',
        'CboManualRuleType', 'TxtManualRuleValue', 'TxtManualRuleDesc', 'CboManualRuleTargetGroup',
        'ChkImportSkipDuplicates', 'ChkExportApprovedOnly'
    )

    It 'Element "<_>" exists in XAML' -ForEach $rulesElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - Policy Panel Elements' {
    $policyElements = @(
        'BtnCreatePolicy',
        'TxtPolicyName', 'TxtPolicyDescription',
        'CboPolicyEnforcement', 'CboPolicyPhase',
        'TxtEditPolicyName', 'TxtEditPolicyDescription',
        'CboEditEnforcement', 'CboEditPhase', 'CboEditTargetGPO', 'TxtEditCustomGPO',
        'BtnSavePolicyChanges'
    )

    It 'Element "<_>" exists in XAML' -ForEach $policyElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - Sidebar and Chrome' {
    $sidebarElements = @(
        'SidebarBorder', 'SidebarColumn', 'SidebarHeader',
        'SidebarTitle', 'SidebarSubtitle',
        'BtnCollapseSidebar', 'NavButtonsPanel', 'NavSeparator',
        'SidebarFooter', 'StatusText', 'DomainText',
        'WorkflowBreadcrumb'
    )

    It 'Element "<_>" exists in XAML' -ForEach $sidebarElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - Workflow Breadcrumb' {
    $breadcrumbElements = @(
        'StageDiscovery', 'StageDiscoveryCount',
        'StageScanner', 'StageScannerCount',
        'StageRules', 'StageRulesCount',
        'StagePolicy', 'StagePolicyCount'
    )

    It 'Element "<_>" exists in XAML' -ForEach $breadcrumbElements {
        $script:AllXamlNames | Should -Contain $_
    }
}

Describe 'XAML Integrity - FindName Cross-Reference' {
    Context 'Dashboard.ps1 references' {
        BeforeAll {
            $script:DashboardRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Dashboard.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Dashboard.ps1 exist in XAML' {
            foreach ($ref in $script:DashboardRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Dashboard.ps1 references '$ref'"
            }
        }
    }

    Context 'ADDiscovery.ps1 references' {
        BeforeAll {
            $script:DiscoveryRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\ADDiscovery.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in ADDiscovery.ps1 exist in XAML' {
            foreach ($ref in $script:DiscoveryRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "ADDiscovery.ps1 references '$ref'"
            }
        }
    }

    Context 'Scanner.ps1 references' {
        BeforeAll {
            $script:ScannerRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Scanner.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Scanner.ps1 exist in XAML' {
            foreach ($ref in $script:ScannerRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Scanner.ps1 references '$ref'"
            }
        }
    }

    Context 'Rules.ps1 references' {
        BeforeAll {
            $script:RulesRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Rules.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Rules.ps1 exist in XAML' {
            foreach ($ref in $script:RulesRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Rules.ps1 references '$ref'"
            }
        }
    }

    Context 'Policy.ps1 references' {
        BeforeAll {
            $script:PolicyRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Policy.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Policy.ps1 exist in XAML' {
            foreach ($ref in $script:PolicyRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Policy.ps1 references '$ref'"
            }
        }
    }

    Context 'Deploy.ps1 references' {
        BeforeAll {
            $script:DeployRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Deploy.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Deploy.ps1 exist in XAML' {
            foreach ($ref in $script:DeployRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Deploy.ps1 references '$ref'"
            }
        }
    }

    Context 'Software.ps1 references' {
        BeforeAll {
            $script:SoftwareRefs = Get-FindNameReferences -FilePath (Join-Path $script:GuiPath 'Panels\Software.ps1') -ExcludeNames $script:DialogOnlyElements
        }

        It 'All FindName references in Software.ps1 exist in XAML' {
            foreach ($ref in $script:SoftwareRefs) {
                $script:AllXamlNames | Should -Contain $ref -Because "Software.ps1 references '$ref'"
            }
        }
    }
}

Describe 'XAML Integrity - No Orphaned Action Tags' {
    It 'XAML has no button Tags that reference non-existent dispatcher actions' {
        # Tags used as filter identifiers, not dispatcher actions
        $nonActionTags = @(
            'FilterRulesAll', 'FilterRulesPublisher', 'FilterRulesHash', 'FilterRulesPath',
            'FilterRulesPending', 'FilterRulesApproved', 'FilterRulesRejected',
            'FilterPoliciesAll', 'FilterPoliciesDraft', 'FilterPoliciesActive',
            'FilterPoliciesDeployed', 'FilterPoliciesArchived',
            'FilterJobsAll', 'FilterJobsPending', 'FilterJobsRunning',
            'FilterJobsCompleted', 'FilterJobsFailed',
            'FilterSoftwareAll', 'FilterSoftwareMatch', 'FilterSoftwareVersionDiff',
            'FilterSoftwareOnlyScan', 'FilterSoftwareOnlyImport',
            'Active',
            'NavDiscovery', 'NavScanner', 'NavRules', 'NavPolicy', 'NavDeploy'
        )

        $orphanedTags = @()
        foreach ($tag in $script:ButtonTags) {
            if ($tag -notin $nonActionTags -and $tag -notin $script:ActionCases) {
                $orphanedTags += $tag
            }
        }

        $orphanedTags | Should -BeNullOrEmpty -Because "All action tags should have dispatcher cases (orphaned: $($orphanedTags -join ', '))"
    }
}
